package com.app.mvvm.model.response


import com.google.gson.annotations.SerializedName

data class EventResponse(
    val adsList: List<Ads>,
    val androidUserVersion: String,
    val androidVendorVersion: String,
    val `data`: List<Data>,
    val dateList: List<String>,
    val iosUserVersion: String,
    val iosVendorVersion: String,
    val isEventCategoryVisible: String,
    val isLatestEventVisible: String,
    val latestEvent: List<LatestEvent>,
    val message: String,
    val status: String,
    val totalPages: String
) {
    data class Ads(
        val adsId: String,
        val adsImage: String,
        val adsImageUrl: String,
        val adsInfo: String,
        val adsName: String,
        val adsType: String,
        val createdDate: String,
        val status: String
    )

    data class Data(
        val ageRestrict: String,
        val clubLayout: String,
        val createdDate: String,
        val currencyType: String,
        val description: String,
        val displayLocation: String,
        val duration: String,
        val durationType: String,
        val eventCategoryId: String,
        val eventCategoryName: String,
        val eventClubLayoutUrl: String,
        val eventDetailId: String,
        val eventId: String,
        val eventImageUrl: String,
        val eventName: String,
        val eventThumbClubLayoutUrl: String,
        val eventThumbImageUrl: String,
        val formateStartDateTime: String,
        val formateStartEventDate: String,
        val formateStartEventMonth: String,
        val formateStartEventTime: String,
        val formatecreatedDate: String,
        val formatedupdatedDate: String,
        val image: String,
        val isAdmin: String,
        val isAds: String,
        val isEnd: String,
        val isFree: String,
        val isGstInclude: String,
        val isMannual: String,
        val isMultiLocation: String,
        val isOfflineTicket: String,
        val isStatus: String,
        val isWishlist: String,
        val language: String,
        val location: String,
        val locationList: List<Location>,
        val mLocation: String,
        val pgCharges: String,
        val priceText: String,
        val redeemed: String,
        val sold: String,
        val startDateTime: String,
        val status: String,
        val ticketPrice: String,
        val tqs: String,
        val twCharges: String,
        val vendorId: String,
        val view: String
    ) {
        data class Location(
            val city: String,
            val displayLocation: String,
            val eventCompleted: String,
            val eventDetailId: String,
            val formateStartDate: String,
            val formateStartDateTime: String,
            val formateStartEventTime: String,
            val latitude: String,
            val location: String,
            val locationStartDateTimeStemp: String,
            val longitude: String,
            val shareEventUrl: String,
            val startDateTimeStemp: String,
            val state: String
        )
    }

    data class LatestEvent(
        val ageRestrict: String,
        val clubLayout: String,
        val createdDate: String,
        val currencyType: String,
        val description: String,
        val displayLocation: String,
        val duration: String,
        val durationType: String,
        val eventCategoryId: String,
        val eventCategoryName: String,
        val eventClubLayoutUrl: String,
        val eventDetailId: String,
        val eventId: String,
        val eventImageUrl: String,
        val eventName: String,
        val eventThumbClubLayoutUrl: String,
        val eventThumbImageUrl: String,
        val formateStartDateTime: String,
        val formateStartEventDate: String,
        val formateStartEventMonth: String,
        val formateStartEventTime: String,
        val formatecreatedDate: String,
        val formatedupdatedDate: String,
        val image: String,
        val isAdmin: String,
        val isEnd: String,
        val isFree: String,
        val isGstInclude: String,
        val isMannual: String,
        val isMultiLocation: String,
        val isOfflineTicket: String,
        val isWishlist: String,
        val language: String,
        val location: String,
        val locationList: List<Location>,
        val mLocation: String,
        val pgCharges: String,
        val priceText: String,
        val redeemed: String,
        val sold: String,
        val startDateTime: String,
        val status: String,
        val ticketPrice: String,
        val tqs: String,
        val twCharges: String,
        val vendorId: String,
        val view: String
    ) {
        data class Location(
            val city: String,
            val displayLocation: String,
            val eventCompleted: String,
            val eventDetailId: String,
            val formateStartDate: String,
            val formateStartDateTime: String,
            val formateStartEventTime: String,
            val latitude: String,
            val location: String,
            val locationStartDateTimeStemp: String,
            val longitude: String,
            val shareEventUrl: String,
            val startDateTimeStemp: String,
            val state: String
        )
    }
}